version: '3.8'

services:
  main-service:
    build:
      context: .
      dockerfile: docker/main.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - slow-api
    networks:
      - app-network

  slow-api:
    build:
      context: .
      dockerfile: docker/slow.Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
